/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Asset as PrismaAsset } from "@prisma/client";

export class AssetServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.AssetCountArgs, "select">): Promise<number> {
    return this.prisma.asset.count(args);
  }

  async assets<T extends Prisma.AssetFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssetFindManyArgs>
  ): Promise<PrismaAsset[]> {
    return this.prisma.asset.findMany<Prisma.AssetFindManyArgs>(args);
  }
  async asset<T extends Prisma.AssetFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssetFindUniqueArgs>
  ): Promise<PrismaAsset | null> {
    return this.prisma.asset.findUnique(args);
  }
  async createAsset<T extends Prisma.AssetCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssetCreateArgs>
  ): Promise<PrismaAsset> {
    return this.prisma.asset.create<T>(args);
  }
  async updateAsset<T extends Prisma.AssetUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssetUpdateArgs>
  ): Promise<PrismaAsset> {
    return this.prisma.asset.update<T>(args);
  }
  async deleteAsset<T extends Prisma.AssetDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AssetDeleteArgs>
  ): Promise<PrismaAsset> {
    return this.prisma.asset.delete(args);
  }
}
