/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Investor as PrismaInvestor } from "@prisma/client";

export class InvestorServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.InvestorCountArgs, "select">): Promise<number> {
    return this.prisma.investor.count(args);
  }

  async investors<T extends Prisma.InvestorFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvestorFindManyArgs>
  ): Promise<PrismaInvestor[]> {
    return this.prisma.investor.findMany<Prisma.InvestorFindManyArgs>(args);
  }
  async investor<T extends Prisma.InvestorFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvestorFindUniqueArgs>
  ): Promise<PrismaInvestor | null> {
    return this.prisma.investor.findUnique(args);
  }
  async createInvestor<T extends Prisma.InvestorCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvestorCreateArgs>
  ): Promise<PrismaInvestor> {
    return this.prisma.investor.create<T>(args);
  }
  async updateInvestor<T extends Prisma.InvestorUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvestorUpdateArgs>
  ): Promise<PrismaInvestor> {
    return this.prisma.investor.update<T>(args);
  }
  async deleteInvestor<T extends Prisma.InvestorDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvestorDeleteArgs>
  ): Promise<PrismaInvestor> {
    return this.prisma.investor.delete(args);
  }
}
